run_zone:
  target:
    entity:
      integration: irrigation_scheduler
      domain: button
  fields:
    duration:
      example: 20
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: min
          mode: box

stop_zone:
  target:
    entity:
      integration: irrigation_scheduler
      domain: button
